services:
  db:
    container_name: agent-play-db
    restart: always
    image: postgres:17
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: agent_play_db
      POSTGRES_PASSWORD: secure-password
      POSTGRES_USER: agent-play-user

  adminer:
    container_name: agent-play-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
