services:
    code:
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        container_name: agents-play-code
        volumes:
            - ../..:/workspaces:cached
        command: sleep infinity
