# List available commands
default:
    just --list --unsorted

# Set up dev container. This step runs after building the dev container
post-create: setup-zsh-environment

[private]
setup-zsh-environment:
    #!/bin/zsh

    echo "Updating zsh configuration"
    cp -f .zshrc ~/.zshrc
